# Generated by Django 4.1.6 on 2023-02-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
